package com.gs.dmn.runtime;

/**
 * Compatibility shim for relation code generated by jDMN 9.0.0.
 * The generator emits com.gs.dmn.runtime.ContextImpl(...), but runtime ships only Context.
 */
public class ContextImpl extends Context {
    public ContextImpl(Object... values) {
        if (values == null) {
            return;
        }

        // Key/value support when constructor is used as ContextImpl("key", value, ...).
        if (values.length % 2 == 0 && values.length > 0 && values[0] instanceof String) {
            for (int i = 0; i < values.length; i += 2) {
                put(values[i], values[i + 1]);
            }
            return;
        }

        // Fallback positional keys keep row values accessible without relying on column names.
        for (int i = 0; i < values.length; i++) {
            put("col" + (i + 1), values[i]);
        }
    }
}
